### PR TITLE
Set mode

### LINKED ISSUE #79: Settings (switch mode)
- [x] add mode switch to pages
- [x] for dark theme in Material components use the "set-mode" component
- [ ] phone-select: country-code dark-mode

deadline 16/02/2021

### PR DESCRIPTION
**Pull request by coriander31415**
- [x] added switch mode toggler to pages (except of 404)
- [x] fixed white lines on pages
- [x] get mode through service
- [x] fix phone background 
- [ ] problem: `this.pathId` is not loaded in `ngOninit()` on-time (src/app/base/pages/projects-page/projects-page.component.ts)
- [x] made settings a separate module
- [x] changed the style of the mode switch
- [x] fix phone-select: country-code dark-mode

### CODE REVIEW

**Comment by kastrubait** [comment]
image

Confused by the size of the switch. Maybe a smaller size will look better? What do you think?

**Comment by coriander31415** [comment]
> 
> Confused by the size of the switch. Maybe a smaller size will look better? What do you think?

@kastrubait 
The size is correlated with other icons.
If you wish, you can try other sizes.
But keep in mind animation before and after switch to not destroy it accidetially!

**Comment by kastrubait** [comment]
problem: this.pathId - solved after splitting into modules and routing settings
- [x] "save" button need to fix styles

image

**Comment by coriander31415** [comment]
> problem: this.pathId - solved after splitting into modules and routing settings
> 
> * [x]  "save" button need to fix styles
> 


- [x] fixed

image

--

- [x] sum flex also fixed:
image

**Pull request merged**
